
CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT UNIQUE NOT NULL,
    full_name TEXT,
    type TEXT,
    location TEXT,
    email UNIQUE TEXT,
    about_me TEXT
);

CREATE TABLE events (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    location TEXT NOT NULL,
    date BIGINT NOT NULL,
    information TEXT
);

CREATE TABLE event_users (
    user_id INTEGER REFERENCES users(id),
    event_id INTEGER REFERENCES events(id),
    role_id INTEGER NOT NULL,
    PRIMARY KEY (user_id, event_id)
)