
CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    profile_name TEXT,
    password TEXT NOT NULL,
    type TEXT,
    location TEXT,
    email TEXT,
    about_me TEXT,
        UNIQUE(name),
        UNIQUE(profile_name),
        UNIQUE(email)
        
);

CREATE TABLE events (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    location TEXT NOT NULL,
    date BIGINT NOT NULL,
    information TEXT
);

CREATE TABLE event_users (
    user_id INTEGER REFERENCES users(id),
    event_id INTEGER REFERENCES events(id),
    role_id INTEGER NOT NULL,
    PRIMARY KEY (user_id, event_id)
)